### ISSUE TITLE
Not visible on latest canary

### ISSUE THREAD

**Issue by divyanshu013** [moso/hyper-dark-scrollbar#4]
Hi, I was earlier using the stable 1.x release of hyper. Recently I changed to the latest canary release and the scrollbar is not showing.

**Comment by moso** [comment]
While I can't test on the canary at the moment, I was wondering if you can test this. Check https://github.com/moso/hyper-dark-scrollbar#attention as the order of plugins apparently matters for Hyper.

So can you test if the issue persists if you load hyper-dark-scrollbar last?

**Comment by divyanshu013** [comment]
Awesome, this was the issue. Thanks!
